# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_cpp_binding', [dirname(__file__)])
        except ImportError:
            import _cpp_binding
            return _cpp_binding
        if fp is not None:
            try:
                _mod = imp.load_module('_cpp_binding', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _cpp_binding = swig_import_helper()
    del swig_import_helper
else:
    import _cpp_binding
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _cpp_binding.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _cpp_binding.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _cpp_binding.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _cpp_binding.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _cpp_binding.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _cpp_binding.SwigPyIterator_equal(self, x)

    def copy(self):
        return _cpp_binding.SwigPyIterator_copy(self)

    def next(self):
        return _cpp_binding.SwigPyIterator_next(self)

    def __next__(self):
        return _cpp_binding.SwigPyIterator___next__(self)

    def previous(self):
        return _cpp_binding.SwigPyIterator_previous(self)

    def advance(self, n):
        return _cpp_binding.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _cpp_binding.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _cpp_binding.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _cpp_binding.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _cpp_binding.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _cpp_binding.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _cpp_binding.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _cpp_binding.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class Line(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Line, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Line, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _cpp_binding.Line_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _cpp_binding.Line___nonzero__(self)

    def __bool__(self):
        return _cpp_binding.Line___bool__(self)

    def __len__(self):
        return _cpp_binding.Line___len__(self)

    def __getslice__(self, i, j):
        return _cpp_binding.Line___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _cpp_binding.Line___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _cpp_binding.Line___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _cpp_binding.Line___delitem__(self, *args)

    def __getitem__(self, *args):
        return _cpp_binding.Line___getitem__(self, *args)

    def __setitem__(self, *args):
        return _cpp_binding.Line___setitem__(self, *args)

    def pop(self):
        return _cpp_binding.Line_pop(self)

    def append(self, x):
        return _cpp_binding.Line_append(self, x)

    def empty(self):
        return _cpp_binding.Line_empty(self)

    def size(self):
        return _cpp_binding.Line_size(self)

    def swap(self, v):
        return _cpp_binding.Line_swap(self, v)

    def begin(self):
        return _cpp_binding.Line_begin(self)

    def end(self):
        return _cpp_binding.Line_end(self)

    def rbegin(self):
        return _cpp_binding.Line_rbegin(self)

    def rend(self):
        return _cpp_binding.Line_rend(self)

    def clear(self):
        return _cpp_binding.Line_clear(self)

    def get_allocator(self):
        return _cpp_binding.Line_get_allocator(self)

    def pop_back(self):
        return _cpp_binding.Line_pop_back(self)

    def erase(self, *args):
        return _cpp_binding.Line_erase(self, *args)

    def __init__(self, *args):
        this = _cpp_binding.new_Line(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _cpp_binding.Line_push_back(self, x)

    def front(self):
        return _cpp_binding.Line_front(self)

    def back(self):
        return _cpp_binding.Line_back(self)

    def assign(self, n, x):
        return _cpp_binding.Line_assign(self, n, x)

    def resize(self, *args):
        return _cpp_binding.Line_resize(self, *args)

    def insert(self, *args):
        return _cpp_binding.Line_insert(self, *args)

    def reserve(self, n):
        return _cpp_binding.Line_reserve(self, n)

    def capacity(self):
        return _cpp_binding.Line_capacity(self)
    __swig_destroy__ = _cpp_binding.delete_Line
    __del__ = lambda self: None
Line_swigregister = _cpp_binding.Line_swigregister
Line_swigregister(Line)

class Array(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Array, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Array, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _cpp_binding.Array_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _cpp_binding.Array___nonzero__(self)

    def __bool__(self):
        return _cpp_binding.Array___bool__(self)

    def __len__(self):
        return _cpp_binding.Array___len__(self)

    def __getslice__(self, i, j):
        return _cpp_binding.Array___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _cpp_binding.Array___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _cpp_binding.Array___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _cpp_binding.Array___delitem__(self, *args)

    def __getitem__(self, *args):
        return _cpp_binding.Array___getitem__(self, *args)

    def __setitem__(self, *args):
        return _cpp_binding.Array___setitem__(self, *args)

    def pop(self):
        return _cpp_binding.Array_pop(self)

    def append(self, x):
        return _cpp_binding.Array_append(self, x)

    def empty(self):
        return _cpp_binding.Array_empty(self)

    def size(self):
        return _cpp_binding.Array_size(self)

    def swap(self, v):
        return _cpp_binding.Array_swap(self, v)

    def begin(self):
        return _cpp_binding.Array_begin(self)

    def end(self):
        return _cpp_binding.Array_end(self)

    def rbegin(self):
        return _cpp_binding.Array_rbegin(self)

    def rend(self):
        return _cpp_binding.Array_rend(self)

    def clear(self):
        return _cpp_binding.Array_clear(self)

    def get_allocator(self):
        return _cpp_binding.Array_get_allocator(self)

    def pop_back(self):
        return _cpp_binding.Array_pop_back(self)

    def erase(self, *args):
        return _cpp_binding.Array_erase(self, *args)

    def __init__(self, *args):
        this = _cpp_binding.new_Array(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _cpp_binding.Array_push_back(self, x)

    def front(self):
        return _cpp_binding.Array_front(self)

    def back(self):
        return _cpp_binding.Array_back(self)

    def assign(self, n, x):
        return _cpp_binding.Array_assign(self, n, x)

    def resize(self, *args):
        return _cpp_binding.Array_resize(self, *args)

    def insert(self, *args):
        return _cpp_binding.Array_insert(self, *args)

    def reserve(self, n):
        return _cpp_binding.Array_reserve(self, n)

    def capacity(self):
        return _cpp_binding.Array_capacity(self)
    __swig_destroy__ = _cpp_binding.delete_Array
    __del__ = lambda self: None
Array_swigregister = _cpp_binding.Array_swigregister
Array_swigregister(Array)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _cpp_binding.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _cpp_binding.StringVector___nonzero__(self)

    def __bool__(self):
        return _cpp_binding.StringVector___bool__(self)

    def __len__(self):
        return _cpp_binding.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _cpp_binding.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _cpp_binding.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _cpp_binding.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _cpp_binding.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _cpp_binding.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _cpp_binding.StringVector___setitem__(self, *args)

    def pop(self):
        return _cpp_binding.StringVector_pop(self)

    def append(self, x):
        return _cpp_binding.StringVector_append(self, x)

    def empty(self):
        return _cpp_binding.StringVector_empty(self)

    def size(self):
        return _cpp_binding.StringVector_size(self)

    def swap(self, v):
        return _cpp_binding.StringVector_swap(self, v)

    def begin(self):
        return _cpp_binding.StringVector_begin(self)

    def end(self):
        return _cpp_binding.StringVector_end(self)

    def rbegin(self):
        return _cpp_binding.StringVector_rbegin(self)

    def rend(self):
        return _cpp_binding.StringVector_rend(self)

    def clear(self):
        return _cpp_binding.StringVector_clear(self)

    def get_allocator(self):
        return _cpp_binding.StringVector_get_allocator(self)

    def pop_back(self):
        return _cpp_binding.StringVector_pop_back(self)

    def erase(self, *args):
        return _cpp_binding.StringVector_erase(self, *args)

    def __init__(self, *args):
        this = _cpp_binding.new_StringVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _cpp_binding.StringVector_push_back(self, x)

    def front(self):
        return _cpp_binding.StringVector_front(self)

    def back(self):
        return _cpp_binding.StringVector_back(self)

    def assign(self, n, x):
        return _cpp_binding.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _cpp_binding.StringVector_resize(self, *args)

    def insert(self, *args):
        return _cpp_binding.StringVector_insert(self, *args)

    def reserve(self, n):
        return _cpp_binding.StringVector_reserve(self, n)

    def capacity(self):
        return _cpp_binding.StringVector_capacity(self)
    __swig_destroy__ = _cpp_binding.delete_StringVector
    __del__ = lambda self: None
StringVector_swigregister = _cpp_binding.StringVector_swigregister
StringVector_swigregister(StringVector)


_cpp_binding.normal_swigconstant(_cpp_binding)
normal = _cpp_binding.normal

_cpp_binding.circulating_swigconstant(_cpp_binding)
circulating = _cpp_binding.circulating

_cpp_binding.image_swigconstant(_cpp_binding)
image = _cpp_binding.image

_cpp_binding.nothing_swigconstant(_cpp_binding)
nothing = _cpp_binding.nothing

def viewMatrixSelector(sceneFileName):
    return _cpp_binding.viewMatrixSelector(sceneFileName)
viewMatrixSelector = _cpp_binding.viewMatrixSelector
class PlanCoverageEstimator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PlanCoverageEstimator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PlanCoverageEstimator, name)
    __repr__ = _swig_repr

    def __init__(self, sceneFileName, sensorSpecs, postProcessing=False, startLocation=None, planLoopsAround=False, printerFriendly=True):
        this = _cpp_binding.new_PlanCoverageEstimator(sceneFileName, sensorSpecs, postProcessing, startLocation, planLoopsAround, printerFriendly)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def evaluatePlan(self, *args):
        return _cpp_binding.PlanCoverageEstimator_evaluatePlan(self, *args)

    def getNumberOfBoxes(self):
        return _cpp_binding.PlanCoverageEstimator_getNumberOfBoxes(self)

    def updateMemoisedEdges(self, allSolutions):
        return _cpp_binding.PlanCoverageEstimator_updateMemoisedEdges(self, allSolutions)

    def getSimplePlans(self):
        return _cpp_binding.PlanCoverageEstimator_getSimplePlans(self)

    def storePlanImage(self, plan, viewMatrix, storagePath):
        return _cpp_binding.PlanCoverageEstimator_storePlanImage(self, plan, viewMatrix, storagePath)

    def getMaxAllowedEnergy(self):
        return _cpp_binding.PlanCoverageEstimator_getMaxAllowedEnergy(self)

    def interpretAndExportPlan(self, plan, arg3, arg4):
        return _cpp_binding.PlanCoverageEstimator_interpretAndExportPlan(self, plan, arg3, arg4)
    __swig_destroy__ = _cpp_binding.delete_PlanCoverageEstimator
    __del__ = lambda self: None
PlanCoverageEstimator_swigregister = _cpp_binding.PlanCoverageEstimator_swigregister
PlanCoverageEstimator_swigregister(PlanCoverageEstimator)

# This file is compatible with both classic and new-style classes.


